# Generated by Django 2.2.13 on 2020-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0006_auto_20160915_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='static/slides/'),
        ),
    ]
