# Generated by Django 2.2.13 on 2020-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0007_auto_20200820_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='signage/static/slides/'),
        ),
    ]
